"""
ScriptGenerator Module
=====================
Generates Python automation scripts from recorded actions.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List


class ScriptGenerator:
    """Generates Python automation scripts from execution recordings."""

    def __init__(self):
        """Initialize ScriptGenerator."""
        pass

    def generate_standalone_script(
        self,
        tc_data: Dict,
        recorded_actions: List[Dict],
        credentials: Dict,
        output_path: str
    ) -> str:
        """
        Generate standalone Python script for test case.

        Args:
            tc_data: Test case data
            recorded_actions: List of recorded action dictionaries
            credentials: Credentials dictionary
            output_path: Path to save script

        Returns:
            Path to generated script
        """
        tc_id = tc_data['tc_id']
        test_scenario = tc_data['test_scenario']

        # Generate imports
        imports = self._generate_imports()

        # Generate class definition
        class_name = self._generate_class_name(tc_id)
        class_init = self._generate_class_init(tc_id, credentials)

        # Generate main test method
        test_method = self._generate_test_method(tc_id, recorded_actions, tc_data)

        # Generate helper methods
        helper_methods = self._generate_helper_methods()

        # Generate main execution block
        main_block = self._generate_main_block(class_name)

        # Combine all parts
        script_content = f'''"""
{tc_id}: {test_scenario} - Standalone Script
{'='*70}
This script automates {tc_id}.

Generated by Test Automation Agent
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Requirements:
    pip install playwright pandas openpyxl
    playwright install chromium

Usage:
    python {Path(output_path).name}
"""

{imports}

class {class_name}:
    """Automation class for {tc_id} test case."""

{class_init}

{test_method}

{helper_methods}

{main_block}
'''

        # Save script
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(script_content)

        return output_path

    def generate_integration_code(
        self,
        tc_data: Dict,
        recorded_actions: List[Dict]
    ) -> Dict:
        """
        Generate code for integration into main automation framework.

        Args:
            tc_data: Test case data
            recorded_actions: List of recorded actions

        Returns:
            Dictionary with method_code and init_code
        """
        tc_id = tc_data['tc_id']
        method_name = tc_id.lower().replace('-', '_')

        # Generate method code
        method_code = self._generate_integration_method(tc_id, recorded_actions, tc_data)

        # Generate init variables
        init_code = f"""        # {tc_id} data storage
        self.{method_name}_verification_results = []
        self.{method_name}_form_data = {{}}
        self.{method_name}_transaction_data = {{}}"""

        return {
            'method_code': method_code,
            'init_code': init_code,
            'method_name': f"{method_name}()"
        }

    def _generate_imports(self) -> str:
        """Generate import statements."""
        return '''import os
import sys
import json
from datetime import datetime
from pathlib import Path
from playwright.sync_api import sync_playwright, expect'''

    def _generate_class_name(self, tc_id: str) -> str:
        """Generate class name from test case ID."""
        # TC_09 -> TC09Automation
        return tc_id.replace('_', '').replace('-', '') + 'Automation'

    def _generate_class_init(self, tc_id: str, credentials: Dict) -> str:
        """Generate __init__ method."""
        email = credentials.get('email', 'user@example.com')
        password = credentials.get('password', 'password')

        return f'''    def __init__(self, headless: bool = False):
        """Initialize {tc_id} automation."""
        self.base_url = "https://qaoneob.remit.in"
        self.headless = headless
        self.browser = None
        self.page = None
        self.context = None
        self.playwright = None

        # Setup directories
        self.base_dir = Path(__file__).parent.parent
        self.reports_dir = self.base_dir / "Reports" / "{tc_id}_Standalone"
        self.reports_dir.mkdir(parents=True, exist_ok=True)

        # Test data storage
        self.form_data = {{}}
        self.transaction_data = {{}}
        self.verification_results = []

        # Credentials
        self.user_email = "{email}"
        self.user_password = "{password}"

    def setup(self):
        """Setup browser and page."""
        print("[SETUP] Launching browser...")
        self.playwright = sync_playwright().start()

        self.browser = self.playwright.chromium.launch(
            headless=self.headless,
            slow_mo=500,
            args=[
                "--start-maximized",
                "--disable-infobars",
                "--no-first-run"
            ]
        )

        self.context = self.browser.new_context(no_viewport=True)
        self.page = self.context.new_page()

        print("[SETUP] Browser launched successfully")

    def teardown(self):
        """Cleanup browser resources."""
        if self.browser:
            self.browser.close()
        if self.playwright:
            self.playwright.stop()
        print("[TEARDOWN] Browser closed")'''

    def _generate_test_method(self, tc_id: str, recorded_actions: List[Dict], tc_data: Dict) -> str:
        """Generate main test method with recorded actions."""
        test_scenario = tc_data['test_scenario']

        # Convert recorded actions to code
        steps_code = ""
        for i, action in enumerate(recorded_actions, 1):
            step_code = self._convert_action_to_code(action, i)
            steps_code += step_code + "\n\n"

        method_code = f'''    def run_{tc_id.lower()}(self) -> bool:
        """
        Execute {tc_id}: {test_scenario}

        Returns:
            bool: True if test passed, False otherwise
        """
        print(f"\\n{{'='*70}}")
        print(f"[EXECUTING] {tc_id}: {test_scenario}")
        print(f"{{'='*70}}")

        try:
{steps_code}
            print(f"\\n{{'='*70}}")
            print(f"[✓] {tc_id}: PASSED")
            print(f"{{'='*70}}")

            return True

        except Exception as e:
            print(f"\\n[✗] {tc_id}: FAILED - {{str(e)}}")
            screenshot_error = self.take_screenshot("{tc_id}_ERROR")
            print(f"[ERROR] Screenshot saved: {{screenshot_error}}")
            return False'''

        return method_code

    def _convert_action_to_code(self, action: Dict, step_no: int) -> str:
        """Convert recorded action to Python code."""
        description = action['description']
        action_type = action['action_type']
        selectors = action.get('selectors_tried', [])

        # Generate step comment and print
        code = f'''            # Step {step_no}: {description}
            print("\\n[STEP {step_no}] {description}")'''

        # Generate action-specific code based on type
        if action_type == 'navigate':
            code += '''
            self.page.goto(f"{self.base_url}/login")
            self.page.wait_for_load_state("networkidle")
            self.page.wait_for_timeout(2000)'''

        elif action_type == 'login':
            code += '''
            email_input = self.page.locator("input[type='email'], input[type='text']").first
            email_input.fill(self.user_email)

            password_input = self.page.locator("input[type='password']").first
            password_input.fill(self.user_password)
            password_input.press("Enter")

            self.page.wait_for_url("**/dashboard", timeout=30000)
            self.page.wait_for_load_state("networkidle")
            self.page.wait_for_timeout(2000)
            print("[STEP {0}] Login successful")'''.format(step_no)

        elif action_type == 'click' and selectors:
            code += f'''
            # Try multiple selectors with retry logic
            element_found = False
            for selector in {selectors}:
                try:
                    element = self.page.locator(selector).first
                    if element.is_visible(timeout=5000):
                        element.click()
                        self.page.wait_for_timeout(2000)
                        element_found = True
                        print(f"[STEP {step_no}] Clicked using selector: {{selector}}")
                        break
                except:
                    continue

            if not element_found:
                raise Exception("Element not found with any selector")'''

        elif action_type == 'scroll':
            code += '''
            self.page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            self.page.wait_for_timeout(2000)'''

        elif action_type == 'wait':
            code += '''
            self.page.wait_for_timeout(3000)'''

        elif action_type == 'verify':
            code += '''
            # Capture form data for verification
            self.form_data = self.page.evaluate("""
                () => {
                    const data = {};
                    document.querySelectorAll('input, select').forEach(el => {
                        if (el.name || el.id) {
                            data[el.name || el.id] = el.value;
                        }
                    });
                    return data;
                }
            """)
            print(f"[STEP {0}] Data captured: {{len(self.form_data)}} fields")'''.format(step_no)

        elif action_type == 'capture':
            code += '''
            # Capture transaction data
            transaction_text = self.page.evaluate("() => document.body.innerText")

            # Extract Booking ID
            import re
            booking_match = re.search(r'Booking ID[\\s\\n]+([A-Z0-9]+)', transaction_text)
            if booking_match:
                self.transaction_data['Booking ID'] = booking_match.group(1)
                print(f"[STEP {0}] Booking ID: {{self.transaction_data['Booking ID']}}")'''.format(step_no)

        else:
            code += f'''
            # Action type: {action_type}
            # Manual implementation required
            self.page.wait_for_timeout(1000)
            print(f"[STEP {step_no}] Action completed")'''

        # Add screenshot
        code += f'''
            screenshot_path = self.take_screenshot("{tc_id}_{step_no:02d}_{self._sanitize_filename(description)}")'''

        return code

    def _generate_integration_method(self, tc_id: str, recorded_actions: List[Dict], tc_data: Dict) -> str:
        """Generate method for integration into main automation class."""
        method_name = tc_id.lower().replace('-', '_')
        test_scenario = tc_data['test_scenario']

        # Convert actions to code
        steps_code = ""
        for i, action in enumerate(recorded_actions, 1):
            step_code = self._convert_action_to_code(action, i)
            # Adjust indentation for class method
            step_code = '\n'.join('    ' + line if line.strip() else line
                                 for line in step_code.split('\n'))
            steps_code += step_code + "\n\n"

        method_code = f'''    def {method_name}(self) -> bool:
        """
        Execute {tc_id}: {test_scenario}

        Returns:
            bool: True if test passed, False otherwise
        """
        tc_id = "{tc_id}"
        print(f"\\n{{'='*70}}")
        print(f"[EXECUTING] {{tc_id}}: {test_scenario}")
        print(f"{{'='*70}}")

        try:
{steps_code}
            print(f"\\n{{'='*70}}")
            print(f"[✓] {{tc_id}}: PASSED")
            print(f"{{'='*70}}")

            return True

        except Exception as e:
            print(f"\\n[✗] {{tc_id}}: FAILED - {{str(e)}}")
            self.take_screenshot(f"{{tc_id}}_ERROR")
            return False'''

        return method_code

    def _generate_helper_methods(self) -> str:
        """Generate helper methods."""
        return '''    def take_screenshot(self, name: str, full_page: bool = False) -> str:
        """Take a screenshot and save it."""
        screenshot_path = self.reports_dir / f"{name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        if full_page:
            self.page.screenshot(path=str(screenshot_path), full_page=True)
        else:
            self.page.screenshot(path=str(screenshot_path))
        print(f"[SCREENSHOT] Saved: {screenshot_path.name}")
        return str(screenshot_path)

    def _sanitize_filename(self, text: str) -> str:
        """Sanitize text for use in filename."""
        sanitized = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in text)
        sanitized = sanitized.replace(' ', '_')
        return sanitized[:50]'''

    def _generate_main_block(self, class_name: str) -> str:
        """Generate main execution block."""
        return f'''
def main():
    """Main execution function."""
    print("\\n" + "="*70)
    print("{class_name} - Standalone Automation")
    print("="*70)
    print(f"Start Time: {{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}}")
    print("="*70)

    automation = {class_name}(headless=False)

    try:
        automation.setup()
        result = automation.run_{class_name.replace('Automation', '').lower()}()

        print("\\n" + "="*70)
        print("EXECUTION SUMMARY")
        print("="*70)
        print(f"Status: {{'PASSED' if result else 'FAILED'}}")
        print(f"End Time: {{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}}")
        print("="*70)

        return 0 if result else 1

    except Exception as e:
        print(f"\\n[CRITICAL ERROR] {{str(e)}}")
        return 1

    finally:
        automation.teardown()


if __name__ == "__main__":
    sys.exit(main())
'''
